# Generated by Django 2.2.5 on 2019-10-15 05:40

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=50, unique=True, verbose_name='사업명')),
                ('Requirements1', models.CharField(blank=True, max_length=50, null=True, verbose_name='요구사항1')),
                ('Requirements2', models.CharField(blank=True, max_length=50, null=True, verbose_name='요구사항2')),
                ('Requirements3', models.CharField(blank=True, max_length=50, null=True, verbose_name='요구사항3')),
                ('support_period', models.FloatField(blank=True, null=True, verbose_name='사업기간')),
                ('support_amount', models.FloatField(blank=True, null=True, verbose_name='지원금액/월')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='참고사항')),
            ],
            options={
                'ordering': ['work_name'],
            },
        ),
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ing', models.CharField(choices=[('상담대기', '상담대기'), ('방문약속', '방문약속'), ('해당안됨', '해당안됨'), ('고민후연락', '고민후연락'), ('재방문요청', '재방문요청'), ('계약완료', '계약완료'), ('거절', '거절'), ('삭제요청', '삭제요청')], default='상담대기', max_length=6, verbose_name='진행')),
                ('support_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='지원금')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 14, 40, 54, 996700), editable=False, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('pay_per', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='수수료율')),
                ('fee_per', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='배당률')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='진행사항')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workings', to='customers.Customer')),
                ('work_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workings', to='supports.Work', to_field='work_name', verbose_name='사업명')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(blank=True, null=True, verbose_name='업무마감일')),
                ('work_category', models.CharField(choices=[('신청서', '신청서'), ('서류심사', '서류심사'), ('승인실사', '승인실사'), ('4대보험취득', '4대보험취득'), ('지원금신청', '지원금신청'), ('기타', '기타')], default='신청서', max_length=50, verbose_name='업무내용')),
                ('work_result', models.CharField(choices=[('진행', '진행'), ('보류', '보류'), ('승인', '승인'), ('불승인', '불승인'), ('완료', '완료'), ('입금완료', '입금완료'), ('취소', '취소')], default='진행', max_length=50, verbose_name='업무결과')),
                ('amount', models.DecimalField(blank=True, decimal_places=0, default=Decimal('0'), max_digits=12, verbose_name='신청지원금')),
                ('amount_duedate', models.DateField(blank=True, null=True, verbose_name='지원금입금예정')),
                ('amount_date', models.DateField(blank=True, null=True, verbose_name='지원금입금일')),
                ('amount_memo', models.TextField(blank=True, null=True, verbose_name='지원금메모')),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 14, 40, 54, 997697), editable=False, verbose_name='등록일')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('pay', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='수수료')),
                ('pay_date', models.DateField(blank=True, null=True, verbose_name='수수료입금일')),
                ('pay_memo', models.TextField(blank=True, null=True, verbose_name='수수료메모')),
                ('fee', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='배당')),
                ('fee_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='지급액')),
                ('fee_date', models.DateField(blank=True, null=True, verbose_name='배당지급일')),
                ('fee_memo', models.TextField(blank=True, null=True, verbose_name='배당메모')),
                ('work_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='supports.Working')),
            ],
            options={
                'ordering': ['work_name', 'work_date'],
            },
        ),
    ]
