# Generated by Django 2.2.5 on 2019-10-18 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 15, 7, 10, 361717), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='working',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 15, 7, 10, 360721), editable=False, verbose_name='등록일'),
        ),
    ]
