# Generated by Django 2.2.5 on 2019-10-18 06:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 15, 7, 10, 344710), editable=False, verbose_name='등록일'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='time_stamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 18, 15, 7, 10, 346704), editable=False, verbose_name='등록일'),
        ),
    ]
