# Generated by Django 2.2.5 on 2019-10-15 05:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2019, 10, 15, 14, 40, 54, 992711), editable=False, verbose_name='등록일')),
                ('company', models.CharField(max_length=50, verbose_name='회사명')),
                ('category', models.CharField(choices=[('내부', '내부'), ('외부', '외부')], default='외부', max_length=6, verbose_name='구분')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('phone', models.CharField(max_length=50, verbose_name='연락처')),
                ('location', models.CharField(choices=[('부산', '부산'), ('김해', '김해'), ('양산', '양산'), ('창원', '창원'), ('울산', '울산'), ('거제/통영', '거제/통영'), ('기타', '기타')], default='부산', max_length=100, verbose_name='지역')),
                ('address', models.CharField(max_length=100, verbose_name='주소')),
                ('bizsub', models.CharField(choices=[('비사업자', '비사업자'), ('제조', '제조'), ('건설', '건설'), ('도소매', '도소매'), ('음식/숙박', '음식/숙박'), ('부동산', '부동산'), ('교육', '교육'), ('운수', '운수'), ('기타', '기타')], default='비사업자', max_length=6, verbose_name='업종')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
                ('sales', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounts.Sales')),
                ('sub_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub', to='customers.Customer')),
            ],
            options={
                'ordering': ['time_stamp'],
            },
        ),
    ]
